services:
  - type: web
    name: telegram-gemini-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8232345435:AAGlHZCx078kNhWJes1ECaGyj7S69X0nS5o
        sync: false
      - key: AIzaSyBqBatEAqsBWMzfIQ65aqT3YeCEY9gAbJ0
        sync: false
